# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('DJANGO', 'Django'), ('FLASK', 'Flask'), ('PYTHON', 'Python'), ('ANGULAR', 'Angular'), ('JAVASCRIPT', 'JavaScript'), ('HTML-CSS', 'HTML-CSS')], default='DJANGO', max_length=10),
        ),
    ]
