# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180607_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='github_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30)),
            ],
        ),
    ]
