# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='github_link',
            field=models.ManyToManyField(to='projects.github_link'),
        ),
    ]
